export const services = [
  {
    id: 1,
    name: 'Hair Cut',
    styles: [
      {
        id: 1,
        name: 'Classic Men Cut',
        category: 'Men',
        price: 100,
        image: 'https://source.unsplash.com/featured/?haircut,men',
      },
      {
        id: 2,
        name: 'Fade / Skin Fade',
        category: 'Men',
        price: 150,
        image: 'https://source.unsplash.com/featured/?fade+haircut',
      },
      {
        id: 3,
        name: 'Layered Cut',
        category: 'Women',
        price: 180,
        image: 'https://source.unsplash.com/featured/?layered+hair',
      },
      {
        id: 4,
        name: 'Bob Cut',
        category: 'Women',
        price: 200,
        image: 'https://source.unsplash.com/featured/?bob+haircut',
      },
      {
        id: 5,
        name: 'Kids Trim',
        category: 'Kids',
        price: 80,
        image: 'https://source.unsplash.com/featured/?kids+haircut',
      },
      {
        id: 6,
        name: 'Kids Bowl Cut',
        category: 'Kids',
        price: 90,
        image: 'https://source.unsplash.com/featured/?child+haircut',
      },
    ],
  },
  {
    id: 2,
    name: 'Hair Color',
    styles: [
      {
        id: 1,
        name: 'Full Hair Color',
        price: 300,
        image: 'https://source.unsplash.com/featured/?haircolor',
      },
      {
        id: 2,
        name: 'Ombre Color',
        price: 350,
        image: 'https://source.unsplash.com/featured/?ombre+hair',
      },
      {
        id: 3,
        name: 'Balayage',
        price: 400,
        image: 'https://source.unsplash.com/featured/?balayage',
      },
      {
        id: 4,
        name: 'Highlights',
        price: 250,
        image: 'https://source.unsplash.com/featured/?highlight+hair',
      },
      {
        id: 5,
        name: 'Root Retouch',
        price: 200,
        image: 'https://source.unsplash.com/featured/?hair+retouch',
      },
      {
        id: 6,
        name: 'Fantasy Color',
        price: 450,
        image: 'https://source.unsplash.com/featured/?fantasy+hair',
      },
      {
        id: 7,
        name: 'Fantasy Color',
        price: 450,
        image: 'https://source.unsplash.com/featured/?fantasy+hair',
      },
    ],
  },
  {
    id: 3,
    name: 'Hair Treatment',
    styles: [
      {
        id: 1,
        name: 'Hot Oil Treatment',
        price: 200,
        image: 'https://source.unsplash.com/featured/?hot+oil+treatment',
      },
      {
        id: 2,
        name: 'Keratin Treatment',
        price: 400,
        image: 'https://source.unsplash.com/featured/?keratin',
      },
      {
        id: 3,
        name: 'Hair Spa',
        price: 300,
        image: 'https://source.unsplash.com/featured/?hair+spa',
      },
      {
        id: 4,
        name: 'Scalp Treatment',
        price: 350,
        image: 'https://source.unsplash.com/featured/?scalp+treatment',
      },
      {
        id: 5,
        name: 'Protein Treatment',
        price: 300,
        image: 'https://source.unsplash.com/featured/?protein+hair',
      },
      {
        id: 6,
        name: 'Hair Mask',
        price: 250,
        image: 'https://source.unsplash.com/featured/?hair+mask',
      },
       {
        id: 7,
        name: 'Hair Mask',
        price: 250,
        image: 'https://source.unsplash.com/featured/?hair+mask',
      },
    ],
  },
  {
    id: 4,
    name: 'Rebond & Forms',
    styles: [
      {
        id: 1,
        name: 'Hair Rebond',
        price: 1000,
        image: 'https://source.unsplash.com/featured/?rebond',
      },
      {
        id: 2,
        name: 'Digital Perm',
        price: 1200,
        image: 'https://source.unsplash.com/featured/?digital+perm',
      },
      {
        id: 3,
        name: 'Brazilian Blowout',
        price: 1300,
        image: 'https://source.unsplash.com/featured/?brazilian+blowout',
      },
      {
        id: 4,
        name: 'Straightening',
        price: 950,
        image: 'https://source.unsplash.com/featured/?hair+straightening',
      },
      {
        id: 5,
        name: 'Cold Perm',
        price: 1100,
        image: 'https://source.unsplash.com/featured/?perm+hair',
      },
      {
        id: 6,
        name: 'Volume Rebond',
        price: 1400,
        image: 'https://source.unsplash.com/featured/?volume+rebond',
      },
      {
        id: 7,
        name: 'Volume Rebond',
        price: 1400,
        image: 'https://source.unsplash.com/featured/?volume+rebond',
      },
    ],
  },
  {
    id: 5,
    name: 'Nail Care',
    styles: [
      {
        id: 1,
        name: 'Manicure',
        price: 100,
        image: 'https://source.unsplash.com/featured/?manicure',
      },
      {
        id: 2,
        name: 'Pedicure',
        price: 120,
        image: 'https://source.unsplash.com/featured/?pedicure',
      },
      {
        id: 3,
        name: 'Nail Art',
        price: 200,
        image: 'https://source.unsplash.com/featured/?nail+art',
      },
      {
        id: 4,
        name: 'Gel Polish',
        price: 180,
        image: 'https://source.unsplash.com/featured/?gel+nails',
      },
      {
        id: 5,
        name: 'Acrylic Nails',
        price: 250,
        image: 'https://source.unsplash.com/featured/?acrylic+nails',
      },
      {
        id: 6,
        name: 'Nail Extension',
        price: 300,
        image: 'https://source.unsplash.com/featured/?nail+extension',
      },
      {
        id: 7,
        name: 'Nail Extension',
        price: 300,
        image: 'https://source.unsplash.com/featured/?nail+extension',
      },
    ],
  },
  {
    id: 6,
    name: 'Foot Spa',
    styles: [
      {
        id: 1,
        name: 'Basic Foot Spa',
        price: 250,
        image: 'https://source.unsplash.com/featured/?foot+spa',
      },
      {
        id: 2,
        name: 'Deluxe Foot Spa',
        price: 350,
        image: 'https://source.unsplash.com/featured/?spa+feet',
      },
      {
        id: 3,
        name: 'Aromatherapy Foot Spa',
        price: 400,
        image: 'https://source.unsplash.com/featured/?aroma+spa',
      },
      {
        id: 4,
        name: 'Foot Scrub',
        price: 300,
        image: 'https://source.unsplash.com/featured/?foot+scrub',
      },
      {
        id: 5,
        name: 'Callus Treatment',
        price: 320,
        image: 'https://source.unsplash.com/featured/?callus+removal',
      },
      {
        id: 6,
        name: 'Hydrating Foot Spa',
        price: 370,
        image: 'https://source.unsplash.com/featured/?hydrating+spa',
      },
      {
        id: 6,
        name: 'Hydrating Foot Spa',
        price: 370,
        image: 'https://source.unsplash.com/featured/?hydrating+spa',
      },
    ],
  },
];
