export const services = [
  {
    id: 1,
    name: 'Hair Cut',
    styles: [
      {
        id: 1,
        name: 'Buzz Cut',
        category: 'Men',
        price: 100,
        image: require('../assets/Haircut/Men/Buzz Cut.webp'),
      },
      {
        id: 2,
        name: 'High Fade',
        category: 'Men',
        price: 100,
        image: require ('../assets/Haircut/Men/High fade.webp'),
      },
      {
        id: 3,
        name: 'Crew Cut',
        category: 'Men',
        price: 100,
        image: require ('../assets/Haircut/Men/Crewcut.webp'),
      },
      {
        id: 4,
        name: 'Fohawk',
        category: 'Men',
        price: 100,
        image: require ('../assets/Haircut/Men/Fohawk.webp'),
      },
       {
        id: 5,
        name: 'French Crop',
        category: 'Men',
        price: 100,
        image: require ('../assets/Haircut/Men/French Crop.webp'),
      },
      {
        id: 6,
        name: 'Side Part',
        category: 'Men',
        price: 100,
        image: require ('../assets/Haircut/Men/Side Part.webp'),
      },
       {
        id: 7,
        name: 'Taper Fade Mohawk',
        category: 'Men',
        price: 100,
        image: require ('../assets/Haircut/Men/Taper Fade Mohawk.webp'),
      },
      {
        id: 8,
        name: 'Textured Comb Over',
        category: 'Men',
        price: 100,
        image: require ('../assets/Haircut/Men/Textured-Comb-Over.webp'),
      },    
      {
        id: 9,
        name: 'Two Block',
        category: 'Men',
        price: 100,
        image: require ('../assets/Haircut/Men/Two Block.webp'),
      },
      {
        id: 10,
        name: 'Burst Fade',
        category: 'Men',
        price: 100,
        image: require ('../assets/Haircut/Men/Burst Fade.webp'),
      },  
      {
        id: 11,
        name: 'Curtain Fringe',
        category: 'Men',
        price: 100,
        image: require ('../assets/Haircut/Men/Curtain Fringe.webp'),
      },  
      {
        id: 12,
        name: 'Army Cut',
        category: 'Men',
        price: 100,
        image: require ('../assets/Haircut/Men/Army Cut.webp'),
      },  
      
      {
        id: 1,
        name: 'Boy Cut',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Boy Cut.webp'),
      },
      {
        id: 2,
        name: 'Butterfly Cut',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Butterfly Cut.webp'),
      },
      {
        id: 3,
        name: 'Fluffy Waves Bob',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Fluffy Waves Bob.webp'),
      },
      {
        id: 4,
        name: 'Layered Curls',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Layered Curls with Bangs.webp'),
      },
      {
        id: 5,
        name: 'Layered',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Layered.webp'),
      },
      {
        id: 6,
        name: 'Long Layered',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Long Layered.webp'),
      }, 
      {
        id: 7,
        name: 'Middy',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Middy.webp'),
      }, 
      {
        id: 8,
        name: 'Short',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Short.webp'),
      }, 
      {
        id: 9,
        name: 'Soft and Pixie Cut',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Soft and Pixie Cut.webp'),
      },         
      {
        id: 10,
        name: 'Textured Bob',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Textured Bob and Wispy Bangs.webp'),
      },   
      {
        id: 11,
        name: 'V Cut',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/V Cut.webp'),
      },   
      {
        id: 12,
        name: 'Wolf Cut Mallet',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Wolf Cut Mullet.webp'),
      },   
      {
        id: 13,
        name: 'Wolf Cut',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Wolf Cut.webp'),
      },  
      {
        id: 14,
        name: 'Bangs',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Bangs.webp'),
      },  
      {
        id: 13,
        name: 'Side swept',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Side swept.webp'),
      },  
      {
        id: 14,
        name: 'Balayage',
        category: 'Women',
        price: 100,
        image: require ('../assets/Haircut/Women/Balayage.webp'),
      },  
      {
        id: 1,
        name: 'Army Cut',
        category: 'Kids',
        price: 100,
        image: require ('../assets/Haircut/Kids/Army Cut.webp'),
      },  
      {
        id: 2,
        name: 'Bowl Cut',
        category: 'Kids',
        price: 100,
        image: require ('../assets/Haircut/Kids/Bowl Cut.webp'),
      },  
      {
        id: 3,
        name: 'Buzz Cut',
        category: 'Kids',
        price: 100,
        image: require ('../assets/Haircut/Kids/Buzz Cut.webp'),
      },  
      {
        id: 4,
        name: 'Comb Over Cut',
        category: 'Kids',
        price: 100,
        image: require ('../assets/Haircut/Kids/Comb Over Cut.webp'),
      },  
      {
        id: 5,
        name: 'Pompadour',
        category: 'Kids',
        price: 100,
        image: require ('../assets/Haircut/Kids/Pompadour.webp'),
      },  
      {
        id: 6,
        name: 'Fade',
        category: 'Kids',
        price: 100,
        image: require ('../assets/Haircut/Kids/Fade.webp'),
      },  
      {
        id: 7,
        name: 'Fringe Fade',
        category: 'Kids',
        price: 100,
        image: require ('../assets/Haircut/Kids/Fringe Fade.webp'),
      },  
      {
        id: 8,
        name: 'High Fade',
        category: 'Kids',
        price: 100,
        image: require ('../assets/Haircut/Kids/High Fade.webp'),
      },  
      {
        id: 9,
        name: 'Mid Fade',
        category: 'Kids',
        price: 100,
        image: require ('../assets/Haircut/Kids/Mid Fade.webp'),
      },  
      {
        id: 10,
        name: 'Mohawk',
        category: 'Kids',
        price: 100,
        image: require ('../assets/Haircut/Kids/Mohawk.webp'),
      },  
      {
        id: 11,
        name: 'Side Part Cut',
        category: 'Kids',
        price: 100,
        image: require ('../assets/Haircut/Kids/Side Part Cut.webp'),
      },  
    ],
  },


  {
    id: 2,
    name: 'Hair Color',
    styles: [
      {
        id: 1,
        name: 'Blonde',
        price: 180,
        image: require ('../assets/Hair Color/Blonde.webp'),
      },
      {
        id: 2,
        name: 'Ash Blonde',
        price: 200,
         image: require ('../assets/Hair Color/Ash Blonde.webp'),
      },
      {
        id: 3,
        name: 'Blue',
        price: 200,
        image: require ('../assets/Hair Color/Blue Hair.webp'),
      },
      {
        id: 4,
        name: 'Burgundy',
        price: 200,
         image: require ('../assets/Hair Color/Burgundy Hair.webp'),
      },
      {
        id: 5,
        name: 'Cherry Red',
        price: 200,
         image: require ('../assets/Hair Color/Cherry Red Hair.webp'),
      },
      {
        id: 6,
        name: 'Chestnut Brown',
        price: 200,
         image: require ('../assets/Hair Color/Chestnut Brown.webp'),
      },
      {
        id: 7,
        name: 'Copper Highlights',
        price: 200,
         image: require ('../assets/Hair Color/Copper Highlights.webp'),
      },
      {
        id: 8,
        name: 'Inky Grey',
        price: 200,
         image: require ('../assets/Hair Color/Inky Grey.webp'),
      },
      {
        id:9,
        name: 'Money Piece Highlights',
        price: 200,
         image: require ('../assets/Hair Color/Money Piece Highlights.webp'),
      },
      {
        id:10,
        name: 'Purple',
        price: 200,
         image: require ('../assets/Hair Color/Purple.webp'),
      },

    ],
  },
  {
    id: 3,
    name: 'Hair Treatment',
    styles: [
      {
        id: 1,
        name: 'Bleaching',
        price: 200,
        image: require('../assets/Hair Treatment/Bleaching.webp'),
      },
      {
        id: 2,
        name: 'Brazillian',
        price: 700,
        image: require('../assets/Hair Treatment/Brazillian.webp'),
      },
      {
        id: 3,
        name: 'Cellophane',
        price: 500,
        image: require('../assets/Hair Treatment/Cellophane.webp'),
      },
      {
        id: 4,
        name: 'Conditioning',
        price: 150,
        image: require('../assets/Hair Treatment/Conditioning.webp'),
      },
      {
        id: 5,
        name: 'Cystiene',
        price: 1500,
        image: require('../assets/Hair Treatment/Cystiene.webp'),
      },
      {
        id: 6,
        name: 'Hair Botox',
        price: 1000,
        image: require('../assets/Hair Treatment/Hair Botox.webp'),
      },
      {
        id: 7,
        name: 'Hair Spa',
        price: 300,
        image: require('../assets/Hair Treatment/Hair Spa.webp'),
      },
      {
        id: 8,
        name: 'Keratin',
        price: 500,
        image: require('../assets/Hair Treatment/Keratin.webp'),
      },
    ],
  },
  {
    id: 4,
    name: 'Rebond & Forms',
    styles: [
      {
        id: 1,
        name: 'Rebond with Botox',
        price: 2000,
        image: require ('../assets/Rebond/Rebond with Botox.webp'),
      },
      {
        id: 2,
        name: 'Rebond with Brazillian',
        price: 1500,
        image: require ('../assets/Rebond/Rebond with Brazillian.webp'),
      },
      {
        id: 3,
        name: 'Rebond with Cellophane',
        price: 1300,
        image: require ('../assets/Rebond/Rebond with Cellophane.webp'),
      },
      {
        id: 4,
        name: 'Rebond with Color',
        price: 2500,
        image: require ('../assets/Rebond/Rebond with Color.webp'),
      },
       {
        id: 5,
        name: 'Rebond with Keratin',
        price: 1000,
        image: require ('../assets/Rebond/Rebond with Keratin.webp'),
      },
    ],
  },


  {
    id: 5,
    name: 'Nail Care',
    styles: [
      {
        id: 1,
        name: 'Manicure',
        price: 100,
        image: 'https://source.unsplash.com/featured/?manicure',
      },
      {
        id: 2,
        name: 'Pedicure',
        price: 120,
        image: 'https://source.unsplash.com/featured/?pedicure',
      },
      {
        id: 3,
        name: 'Nail Art',
        price: 200,
        image: 'https://source.unsplash.com/featured/?nail+art',
      },
      {
        id: 4,
        name: 'Gel Polish',
        price: 180,
        image: 'https://source.unsplash.com/featured/?gel+nails',
      },
      {
        id: 5,
        name: 'Acrylic Nails',
        price: 250,
        image: 'https://source.unsplash.com/featured/?acrylic+nails',
      },
      {
        id: 6,
        name: 'Nail Extension',
        price: 300,
        image: 'https://source.unsplash.com/featured/?nail+extension',
      },
      {
        id: 7,
        name: 'Nail Extension',
        price: 300,
        image: 'https://source.unsplash.com/featured/?nail+extension',
      },
    ],
  },
  {
  id: 6,
  name: 'Foot Spa',
  styles: [
    {
      name: 'Foot Spa Package',
      price: 300,
      images: [
        require('../assets/Foot Spa/Foot Spa.webp'),
        require('../assets/Foot Spa/Manicure.webp'),
        require('../assets/Foot Spa/Pedicure.webp'),
      ],
    },
  ],
}
];
